### ISSUE TITLE
Supports installation under HTTP Proxies

### ISSUE THREAD

**Issue by bruandsbc** [kubeedge/sedna#20]

**Comment by llhuii** [comment]
Ok, here's my notes:
1. there are six environments for setting proxy: `http_proxy/https_proxy/no_proxy/HTTP_PROXY/HTTPS_PROXY/NO_PROXY/
2. we only need to consider the case that installation from source code.

The main places needing to connect internet:
1. docker build: need to add extral args `docker build --build-arg http_proxy --build-arg https_proxy --build-arg no_proxy` 
1. go get/git clone: since it has already inherit these proxy environs, no extra work.

For the cases setting custom repo mirror url:
1. for gm/lc images, edit the gm/lc dockerfiles: 
  -  go: go env -w GOPROXY=
  - alpine apk: 
2. others: just follow the offical instruction to setup

**Comment by llhuii** [comment]
In the release 0.1, we have a all-in-one script for [installation](/docs/setup/install.md#deploy-sedna), so here are the new steps to do:
1. our sedna docker images(e.g. `kubeedge/sedna-gm:v0.1.0`): in each required nodes, need to config docker with [http_proxy/https_proxy](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy)
2. `export http_proxy` when running the install cmd in [installation](/docs/setup/install.md#deploy-sedna)

**Comment by llhuii** [comment]
so I close this.
/close
