### ISSUE TITLE
gm and kb pods are always in pending status

### ISSUE THREAD

**Issue by Congrool** [kubeedge/sedna#95]
**What happened**:
Hello, I tried to install sedna and encountered some problems. I followed the instructions of [Sedna installation document](https://github.com/kubeedge/sedna/blob/main/docs/setup/install.md), while the gm and kb pods were in pending status forever. 

**What you expected to happen**:
gm and kb pods are ready and in running status.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the instructions in [Sedna installation document](https://github.com/kubeedge/sedna/blob/main/docs/setup/install.md).

**Anything else we need to know?**:
I have solved it through adding tolerations to gm and kb deployment in [install.sh](https://github.com/kubeedge/sedna/blob/main/scripts/installation/install.sh). It looks like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb
...
spec:
...
  template:
  ...
    spec:
    ...
      containers:
      ...
        tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
...
```
Modify gm deployment in the same way and do install.sh, then it works.

It confused me that kb deployment and gm deployment use nodeSelector of `sedna: control-plane`,  but they can't tolerate the taint `node-role.kubernetes.io/master:NoSchedule` on master(cloud) node which is labeled as `sedna: control-plane`.

Is there any reason?

**Comment by llhuii** [comment]
Hi, thank you for reporting this problem.

K8s scheduler won't schedule pod to the nodes where taints the pod can tolerlate even you have added the labels.

As said in https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation, by default keadm will mark the master with the taint `node-role.kubernetes.io/master`,  you need to untaint it if you want to run pods(here **KB/GM**) at master nodes.

In current release(v0.3.0), since the sqlite db limit, so we limit KB (and then GM) run at one node, we will optimize this limit and allow KB/GM to run any cloud node.

And more, can you describe your cluster info including:
1. k8s version, kubeedge version
2. number of nodes: cloud node, edge node
3. is cloudcore of kubeedge running at the master node?

**Comment by Congrool** [comment]
@llhuii 
Thank you for your reply.
Actually, there are two nodes in my cluster: 
One master node also with cloudcore running on.
One edge node.

k8s version is 1.19.1, kubeedge version is 1.7.0.

I get what you mean and know the cause of the problem now. 
I wanted to deploy gm and kb at master node and set `SEDNA_GM_NODE=master` , while the gm and kb can't tolerate the taint `node-role.kubernetes.io/master` on master node. And there's no other node (labeled as `sedna: control-plane`) to deploy, thus they are always in pending status.

A more common way to install sedna is to deploy gm and kb on another k8s node with cloudcore running on, instead of the master node.
